# Cost Configuration
# Detailed cost modeling parameters for realistic backtesting

# Commission Models
commissions:
  # Interactive Brokers Tiered Pricing
  interactive_brokers:
    pricing_plan: "tiered"  # tiered, fixed

    # Tiered pricing (per share, with monthly volume discounts)
    tiered:
      # Volume tiers (monthly shares traded)
      tiers:
        - volume_threshold: 0
          per_share: 0.0035
          minimum: 0.35
          maximum: 0.01  # 1% of trade value
        - volume_threshold: 300000
          per_share: 0.0020
          minimum: 0.35
          maximum: 0.01
        - volume_threshold: 3000000
          per_share: 0.0015
          minimum: 0.35
          maximum: 0.01
        - volume_threshold: 20000000
          per_share: 0.0010
          minimum: 0.35
          maximum: 0.01
        - volume_threshold: 100000000
          per_share: 0.0005
          minimum: 0.35
          maximum: 0.01

    # Regulatory fees
    regulatory_fees:
      sec_fee: 0.0000278  # SEC Section 31 fee (per dollar sold)
      finra_taf: 0.000145  # FINRA Trading Activity Fee (per share, max $8.30)
      finra_taf_max: 8.30

  # TD Ameritrade
  td_ameritrade:
    stocks: 0.0  # Free stock trading
    options_contract: 0.65

  # Custom flat commission
  custom_flat:
    per_trade: 5.00
    per_share: 0.0

# Spread Models
spreads:
  # Fixed spread (basis points)
  fixed:
    equities:
      large_cap: 2.0     # 2 bps for large cap (e.g., SPY)
      mid_cap: 5.0       # 5 bps for mid cap
      small_cap: 10.0    # 10 bps for small cap

    forex:
      major_pairs: 1.0   # 1 bp for EUR/USD, etc.
      minor_pairs: 3.0   # 3 bps
      exotic_pairs: 10.0 # 10 bps

    commodities:
      energy: 5.0        # WTI, Natural Gas
      metals: 3.0        # Gold, Silver, Copper
      agriculture: 8.0   # Wheat, Corn, Soybeans

  # Time-varying spread multipliers
  intraday_patterns:
    market_open_minutes: 30
    market_close_minutes: 30
    open_multiplier: 2.0    # Spreads 2x wider at open
    close_multiplier: 1.5   # Spreads 1.5x wider at close
    lunch_multiplier: 1.2   # Spreads 1.2x wider during lunch (11:30-13:30)

  # Volume-dependent spread
  volume_impact:
    enabled: true
    # Participation rate thresholds
    thresholds:
      - participation_rate: 0.01  # < 1% of volume
        multiplier: 1.0
      - participation_rate: 0.05  # 1-5% of volume
        multiplier: 1.5
      - participation_rate: 0.10  # 5-10% of volume
        multiplier: 2.5
      - participation_rate: 0.20  # > 10% of volume
        multiplier: 4.0

  # Volatility-based spread
  volatility_impact:
    enabled: true
    base_vol: 0.15      # 15% annualized base volatility
    vol_elasticity: 0.5 # Spread increases by 50% for each doubling of vol

# Market Impact Models
market_impact:
  # Almgren-Chriss parameters
  almgren_chriss:
    # Temporary impact (mean-reversion)
    eta: 0.0001         # Price impact per dollar traded (temporary)

    # Permanent impact
    gamma: 0.00001      # Price impact per share (permanent)

    # Volatility scaling
    volatility_adjustment: true

    # Volume scaling
    adv_scaling: true   # Scale by average daily volume

  # Simple square-root impact
  sqrt_impact:
    lambda: 0.10        # Impact coefficient (bps per sqrt(participation_rate))

  # Linear impact
  linear_impact:
    lambda: 1.0         # Impact coefficient (bps per participation_rate)

  # Intraday patterns
  intraday_multipliers:
    enabled: true
    market_open_hours: 1    # First hour
    market_close_hours: 1   # Last hour
    open_multiplier: 1.5
    close_multiplier: 1.3

# Slippage Models
slippage:
  # Fixed slippage
  fixed:
    equities: 5.0       # 5 bps
    forex: 2.0          # 2 bps
    commodities: 8.0    # 8 bps

  # Dynamic slippage components
  dynamic:
    # Base slippage
    base_slippage_bps: 5.0

    # Volume component
    volume_component:
      enabled: true
      coefficient: 10.0  # bps per 1% participation rate

    # Volatility component
    volatility_component:
      enabled: true
      coefficient: 20.0  # bps per unit volatility

    # Time of day component
    time_component:
      enabled: true
      open_premium_bps: 3.0
      close_premium_bps: 2.0

    # Adverse selection
    adverse_selection:
      enabled: true
      coefficient: 5.0   # bps for informed trading

    # Bounds
    min_slippage_bps: 1.0
    max_slippage_bps: 50.0

# Borrow Costs (Short Selling)
borrow_costs:
  # General collateral (easy-to-borrow)
  general_collateral:
    rate: 0.005         # 0.5% annualized

  # Tiered by market cap
  tiered:
    large_cap: 0.003    # 0.3% (large cap, liquid)
    mid_cap: 0.010      # 1.0% (mid cap)
    small_cap: 0.050    # 5.0% (small cap, harder to borrow)

  # Hard-to-borrow
  hard_to_borrow:
    rate: 0.20          # 20% annualized
    threshold_availability: 0.10  # If <10% available, considered HTB

  # Recall risk
  recall_risk:
    enabled: true
    probability_per_day: 0.001  # 0.1% chance of recall per day for HTB

  # Dividend obligations
  dividends:
    pass_through: true  # Short seller must pay dividends
    withholding_tax: 0.30  # 30% withholding on foreign dividends

# Funding Costs
funding:
  # Margin interest rates
  margin_interest:
    # Tiered by account balance
    tiers:
      - balance_threshold: 0
        rate: 0.0833      # 8.33% (base rate)
      - balance_threshold: 100000
        rate: 0.0733      # 7.33% (>100k)
      - balance_threshold: 1000000
        rate: 0.0633      # 6.33% (>1M)
      - balance_threshold: 3000000
        rate: 0.0583      # 5.83% (>3M)

    # Account type multipliers
    account_types:
      retail: 1.0
      professional: 0.8
      institutional: 0.6

  # Overnight funding (CFDs, FX)
  overnight_funding:
    enabled: true
    reference_rate: 0.05  # 5% base rate
    spread: 0.025         # 2.5% spread over reference

  # Currency carry
  currency_carry:
    enabled: true
    # Interest rate differentials (if data not available)
    # Positive = earn carry, Negative = pay carry
    default_rates:
      USD: 0.05
      EUR: 0.03
      JPY: -0.01
      AUD: 0.04
      GBP: 0.05

  # Leverage costs (non-linear)
  leverage_costs:
    enabled: true
    # Incremental cost per leverage level
    brackets:
      - leverage_threshold: 1.0
        additional_rate: 0.0
      - leverage_threshold: 1.5
        additional_rate: 0.01  # +1% above 1.5x
      - leverage_threshold: 2.0
        additional_rate: 0.02  # +2% above 2.0x
      - leverage_threshold: 3.0
        additional_rate: 0.05  # +5% above 3.0x

# Tax Models
taxes:
  # US Tax Rates (2024)
  us:
    # Federal rates
    federal:
      short_term:
        # Ordinary income tax brackets
        brackets:
          - threshold: 0
            rate: 0.10
          - threshold: 11000
            rate: 0.12
          - threshold: 44725
            rate: 0.22
          - threshold: 95375
            rate: 0.24
          - threshold: 182100
            rate: 0.32
          - threshold: 231250
            rate: 0.35
          - threshold: 578125
            rate: 0.37

      long_term:
        # Long-term capital gains (held > 365 days)
        brackets:
          - threshold: 0
            rate: 0.00
          - threshold: 44625
            rate: 0.15
          - threshold: 492300
            rate: 0.20

    # State taxes (California example)
    state:
      rate: 0.133  # 13.3% top rate

    # Net investment income tax
    niit:
      enabled: true
      rate: 0.038       # 3.8% Medicare surtax
      threshold: 200000 # Single filer

  # Wash sale rules
  wash_sale:
    enabled: true
    lookback_days: 30
    lookforward_days: 30

  # Lot matching methods
  lot_matching:
    default: "FIFO"  # FIFO, LIFO, HIFO, SpecificID, MinTax

    # Tax loss harvesting
    tax_loss_harvesting:
      enabled: true
      min_loss_threshold: 1000  # Harvest if loss > $1000
      max_correlation: 0.80     # Max correlation for replacement security

# Exchange Fees
exchange_fees:
  # US Exchanges
  nyse:
    maker_rebate: -0.0020   # -$0.0020 per share (rebate)
    taker_fee: 0.0030       # $0.0030 per share
    max_fee_pct: 0.0030     # 0.30% of trade value cap

  nasdaq:
    maker_rebate: -0.0018
    taker_fee: 0.0030
    max_fee_pct: 0.0030

  # ASX (Australian Securities Exchange)
  asx:
    clearing_fee: 0.00015   # 0.015% (15 bps)
    settlement_fee: 0.00001 # 0.001% (0.1 bps)

# Currency Conversion
currency_conversion:
  # FX conversion costs
  conversion_spread: 0.0010  # 10 pips (0.10%)

  # Bank/broker fees
  conversion_fee: 0.0002     # 2 bps

  # Real-time FX rates
  use_historical_fx: true    # Use actual historical FX rates

# Cost Aggregation
aggregation:
  # Cost ceiling (max total cost)
  max_total_cost_pct: 0.05   # 5% of trade value

  # Warning thresholds
  warnings:
    high_cost_threshold: 0.02  # Warn if costs > 2%
    high_impact_threshold: 0.01  # Warn if impact > 1%

# Cost Reporting
reporting:
  # Breakdown by component
  detailed_breakdown: true

  # Aggregate statistics
  summary_statistics: true

  # Cost attribution
  cost_attribution:
    - commissions
    - spreads
    - market_impact
    - slippage
    - borrow_costs
    - funding_costs
    - taxes
    - exchange_fees

# Model Selection
active_models:
  commission: "interactive_brokers"
  spread: "dynamic"
  market_impact: "almgren_chriss"
  slippage: "dynamic"
  borrow_cost: "tiered"
  funding: "tiered"
  tax: "us"
