# Quantitative Trading System Configuration

# System Settings
system:
  name: "Quantitative Trading System"
  version: "1.0.0"
  environment: "development"  # development, staging, production
  timezone: "UTC"

# Trading Instruments Configuration
instruments:
  commodities:
    WTI:
      symbol: "CL"
      name: "WTI Crude Oil"
      exchange: "NYMEX"
      contract_size: 1000
      tick_size: 0.01
      currency: "USD"
      data_source: "primary"
      trading_hours: "00:00-23:59"

    GOLD:
      symbol: "GC"
      name: "Gold Futures"
      exchange: "COMEX"
      contract_size: 100
      tick_size: 0.10
      currency: "USD"
      data_source: "primary"
      trading_hours: "00:00-23:59"

    COPPER:
      symbol: "HG"
      name: "Copper Futures"
      exchange: "COMEX"
      contract_size: 25000
      tick_size: 0.0005
      currency: "USD"
      data_source: "primary"
      trading_hours: "00:00-23:59"

  indices:
    SPY:
      symbol: "SPY"
      name: "SPDR S&P 500 ETF"
      exchange: "NYSE"
      type: "ETF"
      currency: "USD"
      data_source: "primary"
      trading_hours: "09:30-16:00"

    QQQ:
      symbol: "QQQ"
      name: "Invesco QQQ Trust"
      exchange: "NASDAQ"
      type: "ETF"
      currency: "USD"
      data_source: "primary"
      trading_hours: "09:30-16:00"

    ASX:
      symbol: "XJO"
      name: "S&P/ASX 200 Index"
      exchange: "ASX"
      type: "INDEX"
      currency: "AUD"
      data_source: "primary"
      trading_hours: "10:00-16:00"

  forex:
    AUDUSD:
      symbol: "AUD/USD"
      base_currency: "AUD"
      quote_currency: "USD"
      pip_size: 0.0001
      lot_size: 100000
      leverage: 50
      data_source: "primary"
      trading_hours: "00:00-23:59"

    USDJPY:
      symbol: "USD/JPY"
      base_currency: "USD"
      quote_currency: "JPY"
      pip_size: 0.01
      lot_size: 100000
      leverage: 50
      data_source: "primary"
      trading_hours: "00:00-23:59"

    EURUSD:
      symbol: "EUR/USD"
      base_currency: "EUR"
      quote_currency: "USD"
      pip_size: 0.0001
      lot_size: 100000
      leverage: 50
      data_source: "primary"
      trading_hours: "00:00-23:59"

# Risk Management Parameters
risk_management:
  # Portfolio Level
  portfolio:
    annual_volatility_target: 0.20  # 20% annual volatility target
    max_portfolio_leverage: 2.0
    max_correlation_threshold: 0.85
    rebalance_frequency: "daily"

  # Position Level
  position:
    max_position_risk: 0.02  # 2% max risk per position
    max_position_size: 0.15  # 15% max allocation per position
    min_position_size: 0.01  # 1% min allocation
    stop_loss_multiplier: 2.0  # ATR multiplier for stop loss
    take_profit_multiplier: 3.0  # ATR multiplier for take profit

  # Drawdown Controls
  drawdown:
    max_drawdown: 0.20  # 20% maximum drawdown
    drawdown_lookback_days: 252
    recovery_threshold: 0.10  # Resume trading when drawdown recovers to 10%

  # Risk Metrics
  metrics:
    var_confidence: 0.95  # 95% Value at Risk
    cvar_confidence: 0.95  # 95% Conditional Value at Risk
    sharpe_target: 1.5
    sortino_target: 2.0

# Data Configuration
data:
  # Data Sources
  sources:
    primary:
      provider: "alpha_vantage"  # alpha_vantage, yahoo_finance, polygon, etc.
      api_endpoint: "${ALPHA_VANTAGE_ENDPOINT}"
      rate_limit: 5  # requests per minute

    secondary:
      provider: "yahoo_finance"
      api_endpoint: "https://query1.finance.yahoo.com"
      rate_limit: 100

  # Data Storage
  storage:
    database:
      type: "postgresql"
      host: "${DB_HOST}"
      port: 5432
      database: "${DB_NAME}"
      user: "${DB_USER}"
      password: "${DB_PASSWORD}"

    cache:
      type: "redis"
      host: "${REDIS_HOST}"
      port: 6379
      ttl: 3600  # seconds

  # Data Parameters
  parameters:
    lookback_days: 252  # 1 year of historical data
    update_frequency: "1min"  # 1min, 5min, 15min, 1hour, 1day
    data_quality_threshold: 0.95
    missing_data_method: "forward_fill"  # forward_fill, interpolate, drop

# Execution Configuration
execution:
  # Broker Configuration
  broker:
    name: "interactive_brokers"
    account_id: "${IB_ACCOUNT_ID}"
    api_host: "${IB_API_HOST}"
    api_port: "${IB_API_PORT}"
    client_id: "${IB_CLIENT_ID}"

  # Order Management
  orders:
    default_order_type: "LIMIT"  # MARKET, LIMIT, STOP, STOP_LIMIT
    time_in_force: "DAY"  # DAY, GTC, IOC, FOK
    slippage_model: "linear"  # linear, square_root, logarithmic
    estimated_slippage: 0.0005  # 5 basis points

  # Execution Algorithms
  algorithms:
    twap:
      enabled: true
      time_window: 300  # seconds

    vwap:
      enabled: true
      volume_participation: 0.10  # 10% of volume

    iceberg:
      enabled: true
      visible_ratio: 0.20  # 20% visible

# Backtesting Configuration
backtesting:
  # Simulation Parameters
  simulation:
    start_date: "2020-01-01"
    end_date: "2023-12-31"
    initial_capital: 1000000
    commission: 0.0010  # 10 basis points
    slippage: 0.0005  # 5 basis points

  # Performance Metrics
  metrics:
    calculate_sharpe: true
    calculate_sortino: true
    calculate_calmar: true
    calculate_max_drawdown: true
    calculate_var: true
    calculate_cvar: true

  # Optimization
  optimization:
    method: "grid_search"  # grid_search, random_search, bayesian
    metric: "sharpe_ratio"
    parameter_ranges:
      lookback_period: [10, 20, 50, 100, 200]
      threshold: [0.5, 1.0, 1.5, 2.0, 2.5]

# Strategy Configuration
strategies:
  # Momentum Strategy
  momentum:
    enabled: true
    lookback_period: 20
    holding_period: 5
    rebalance_frequency: "daily"
    universe_size: 10
    entry_threshold: 2.0  # z-score
    exit_threshold: 0.5

  # Mean Reversion Strategy
  mean_reversion:
    enabled: true
    lookback_period: 30
    bollinger_bands:
      period: 20
      std_dev: 2.0
    rsi:
      period: 14
      overbought: 70
      oversold: 30

  # Arbitrage Strategy
  arbitrage:
    enabled: false
    pairs_correlation_threshold: 0.80
    z_score_entry: 2.0
    z_score_exit: 0.5
    lookback_period: 60

# Machine Learning Configuration
ml:
  # Model Parameters
  models:
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 5

    xgboost:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.01

    lstm:
      hidden_units: 128
      dropout: 0.2
      epochs: 100
      batch_size: 32

  # Feature Engineering
  features:
    technical_indicators: ["SMA", "EMA", "RSI", "MACD", "BB", "ATR"]
    lookback_windows: [5, 10, 20, 50]
    include_volume: true
    include_sentiment: false

# Monitoring Configuration
monitoring:
  # Alerts
  alerts:
    email:
      enabled: true
      recipients: ["${ALERT_EMAIL}"]
      smtp_server: "${SMTP_SERVER}"
      smtp_port: 587

    slack:
      enabled: false
      webhook_url: "${SLACK_WEBHOOK}"

  # Thresholds
  thresholds:
    drawdown_alert: 0.10  # Alert at 10% drawdown
    daily_loss_alert: 0.05  # Alert at 5% daily loss
    position_limit_alert: 0.90  # Alert at 90% of position limit

  # Reporting
  reporting:
    daily_report: true
    weekly_report: true
    monthly_report: true
    report_time: "17:00"  # UTC

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  rotation: "100 MB"
  retention: "30 days"
  compression: "zip"

  # Log Files
  files:
    main: "logs/trading_system.log"
    trades: "logs/trades.log"
    errors: "logs/errors.log"
    performance: "logs/performance.log"